version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: missao_app
    volumes:
      - ./:/var/www
    networks:
      - missao-net
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: missao_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - missao-net

  db:
    image: mysql:8.0
    container_name: missao_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: missao
      MYSQL_USER: pimenta
      MYSQL_PASSWORD: 13151319
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - missao-net

volumes:
  dbdata:

networks:
  missao-net:
    driver: bridge
